# Generated by Django 4.0.1 on 2022-02-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexique',
            name='user',
        ),
    ]
