# Generated by Django 4.0.1 on 2022-02-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0005_trophy_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trophy',
        ),
    ]
