# Generated by Django 4.0.1 on 2022-02-15 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0007_remove_score_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
