# Generated by Django 4.0.1 on 2022-02-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0009_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
