# Generated by Django 4.0.1 on 2022-02-16 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0010_delete_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
