# Generated by Django 4.0.1 on 2022-02-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lexique', '0014_lexique_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexique',
            name='user',
        ),
    ]
