# Generated by Django 4.0.1 on 2022-03-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_alter_score_maneki_alter_trophy_user_trophy'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_hiragana',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
