# Generated by Django 4.0.1 on 2022-03-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_score_score_hiragana'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score_katakana',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
