# Generated by Django 4.0.1 on 2022-03-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_score_score_katakana'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='last_game',
            field=models.DateTimeField(null=True),
        ),
    ]
