# Generated by Django 4.0.1 on 2022-02-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_trophy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophy',
            old_name='scores_max',
            new_name='score_max',
        ),
        migrations.RenameField(
            model_name='trophy',
            old_name='scores_min',
            new_name='score_min',
        ),
    ]
