# Generated by Django 4.0.1 on 2022-02-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_rename_scores_max_trophy_score_max_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trophy',
        ),
    ]
