# Generated by Django 4.0.1 on 2022-02-15 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_trophy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='user',
        ),
    ]
