# Generated by Django 4.0.1 on 2022-02-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_remove_trophy_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trophy',
        ),
    ]
