# Generated by Django 4.0.1 on 2022-02-15 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_delete_trophy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Score',
        ),
    ]
