# Generated by Django 4.0.1 on 2022-02-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_trophy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trophy',
            old_name='Img_link',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='trophy',
            old_name='name',
            new_name='trophy_name',
        ),
        migrations.RenameField(
            model_name='trophy',
            old_name='score_max',
            new_name='trophy_score_max',
        ),
        migrations.RenameField(
            model_name='trophy',
            old_name='score_min',
            new_name='trophy_score_min',
        ),
    ]
