# Generated by Django 4.0.1 on 2022-02-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_rename_img_link_trophy_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='user',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Trophy',
        ),
    ]
